services:
  www:
    image: nginx:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.www.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.www.entrypoints=websecure"
      - "traefik.http.routers.www.tls.certresolver=myresolver"
    networks:
      - web

networks:
  web:
    name: web
    external: true
