services:
  www:
    container_name: www
    image: nginx:alpine
    restart: always
    env_file:
      - .env
    volumes:
      - "./html:/usr/share/nginx/html:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      - "traefik.http.routers.www.rule=Host(\"${DOMAIN}\")"
      - "traefik.http.routers.www.entrypoints=web,websecure"
      - "traefik.http.routers.www.tls.certresolver=myresolver"

      - "traefik.http.routers.www.middlewares=use-nginx-middleware"
    networks:
      - web

networks:
  web:
    name: web
    external: true
