name: Call Shared Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-shared-workflow:
    uses: deljdlx/github-tools/.github/workflows/update-main-readme.yml@main
    secrets:
        personal_access_token: ${{ secrets.ACTION_TOKEN }}